runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: ssl
  version: latest

env_variables:
  GAE_USE_SOCKETS_HTTPLIB : 'true'

# [START handlers]
handlers:
- url: /static
  static_dir: static
  application_readable: true
- url: /.*
  script: main.app
# [END handlers]
